// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import config from "dotenv";
import path from "path";
import { defineConfig, env } from "prisma/config";

// Force load .env.local from project root
config.config({ path: path.resolve(process.cwd(), ".env.local") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: env("DATABASE_URL"),
  },
});