import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 md:py-24 space-y-8">
      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full glass-panel-purple text-xs font-mono text-purple-300">
        Legal & Compliance
      </div>
      
      <h1 className="text-3xl md:text-4xl font-medium tracking-tight text-white">
        Terms & Conditions
      </h1>
      
      <div className="space-y-8 text-sm text-zinc-300 leading-relaxed font-light glass-panel p-8 rounded-2xl">
        <section className="space-y-2">
          <h2 className="text-lg font-medium text-white">1. Acceptance of Terms</h2>
          <p className="text-zinc-400">
            By accessing and using VectoFace AI, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you are prohibited from using our biometric analysis services.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-medium text-purple-400">2. Acceptable Use & Consent</h2>
          <p className="text-zinc-400">
            You may only upload photos of yourself. By uploading an image, you confirm that you are the individual depicted or have explicit, legally valid consent from the individual. VectoFace AI is designed for personal, non-medical aesthetic analysis only.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-medium text-white">3. Medical Disclaimer</h2>
          <p className="text-zinc-400">
            The reports generated by VectoFace AI are based on geometric algorithms and population averages. <strong className="text-zinc-200">Our analysis is strictly for entertainment and self-improvement purposes. It does not constitute medical advice, nor should it be used for diagnosing dysmorphia, structural conditions, or any health-related issues.</strong>
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-medium text-white">4. Intellectual Property</h2>
          <p className="text-zinc-400">
            The algorithms, UI design, branding, and proprietary "Neural Structure Mapping" technology are the exclusive property of VectoFace AI. You may not reverse-engineer, scrape, or resell our reports.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-medium text-white">5. Governing Law</h2>
          <p className="text-zinc-400">
            These terms are governed by the laws of India. Any disputes arising out of the use of this website will be subject to the exclusive jurisdiction of the courts located in India.
          </p>
        </section>
      </div>
    </div>
  );
}